[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
json = "0.12.4"
serde = "1.0.197"
uuid = "1.7.0"
validator = "0.16.1"
